accumulate_grad_batches: 1
amp_level: O1
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 256
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
default_root_dir: null
deterministic: false
distributed_backend: null
dropout: 0.1
early_stop_callback: false
embedding_dim: 256
fast_dev_run: false
gpus: 0,
gradient_clip_val: 1.0
hidden_dim: 256
log_gpu_memory: null
log_save_interval: 100
logger: true
lr: 0.0003
max_epochs: 1000
max_steps: null
min_epochs: 1
min_steps: null
num_fertility: 9
num_gate: 3
num_heads: 4
num_nodes: 1
num_passes: 2
num_processes: 1
num_sanity_val_steps: 2
num_tpu_cores: null
ontology_path: ./.data/MultiWoz_2.1_NADST_Version/data2.1/multi-woz/MULTIWOZ2.1/ontology.json
overfit_pct: 0.0
precision: 32
print_nan_grads: false
process_position: 0
profiler: null
progress_bar_callback: true
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
row_log_interval: 10
terminate_on_nan: false
test_path: ./.data/MultiWoz_2.1_NADST_Version/data2.1/nadst_test_dials.json
test_percent_check: 1.0
tokenizer_path: ./tokenizer/multiwoz2.1-vocab.json
track_grad_norm: -1
train_path: ./.data/MultiWoz_2.1_NADST_Version/data2.1/nadst_train_dials.json
train_percent_check: 1.0
truncated_bptt_steps: null
val_check_interval: 1.0
val_path: ./.data/MultiWoz_2.1_NADST_Version/data2.1/nadst_dev_dials.json
val_percent_check: 1.0
weight_decay: 0
weights_save_path: null
weights_summary: full
